Skeleton_2
js-tasks-ru/htmlcss-20211021_maestroat pull request #16
Opened 2021-11-12 08:19 UTC by TimofeevAnton1980

Задача Скелетон

2021-11-12 08:19 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-11-16 08:22 UTC, TimofeevAnton1980 commented
Виноват, в последней правке случайно в блок .skeleton пропала св-во margin - это ошибка при копировании из файла, он роли не играет и в следующей версии я его удалю. А как в остальном, норм.?

2021-11-17 13:46 UTC, GSemikozov requested changes

2021-11-17 13:46 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 15%;
а если картинка (64px) не влезет в такую ширину (15%)?)

2021-11-17 13:46 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 15%;
обычный display: flex и так по умолчанию поставил два блока в один ряд (то чего мы и достигаем явным указанием ширина каждого из блоков в процентах)

2021-11-17 13:46 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    margin: 20px;
вместо марджина здесь и марджина сверху у хедера лучше задать один раз общие паддинги на уровне всего блока .skeleton

2021-11-17 20:41 UTC, TimofeevAnton1980 commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 15%;
тогда перестает отображаться  блок с боковыми линиями, если не задать ему ширину

2021-11-18 09:03 UTC, TimofeevAnton1980 commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 15%;
Кажется нашел решение. Вечером перешлю.

2021-11-18 09:09 UTC, TimofeevAnton1980 commented on 04-lection2/02-skeleton/skeleton.css
> +    margin: 20px;
Да. Лучше

2021-11-18 19:45 UTC, GSemikozov requested changes

2021-11-18 19:45 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    margin-left: 10px;
12px

2021-11-18 19:45 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 60%;
calc(100% - 64px - 12px)

2021-11-18 19:45 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +@media screen and (max-width: 540px) {
и тогда 2 последующих медиа-запроса будут лишними

2021-11-19 05:40 UTC, TimofeevAnton1980 commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 60%;
да, хитрооо

2021-11-19 05:40 UTC, TimofeevAnton1980 commented on 04-lection2/02-skeleton/skeleton.css
> +@media screen and (max-width: 540px) {
да

2021-11-19 18:02 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-11-19 21:26 UTC, GSemikozov approved these changes

2021-11-19 21:26 UTC, merged