tooltip
js-tasks-ru/htmlcss-20211021_maestroat pull request #18
Opened 2021-11-13 13:28 UTC by TimofeevAnton1980

2021-11-13 13:28 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-11-14 11:38 UTC, GSemikozov requested changes

2021-11-14 11:38 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    position: relative;
`position: relative;`. надо задать на уровне блока, поскольку для всплывашки именно блок - родитель относительно которого она позиционируется

2021-11-14 11:38 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    transform: translate(-50%,-190%);
-190% - анти-паттерн, поскольку идет привязка отступа от элемента собственно к размерам этого элемента. Правильнее будет например указать bottom: 100%,  а в translate значение которое всегда будет фиксированным не зависимо от размеров триггера, например 8px

2021-11-14 11:38 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +.tooltip__strelka {
стрелка не доделана?

2021-11-14 12:17 UTC, TimofeevAnton1980 commented on 05-lection3/01-tooltip/tooltip.css
> +.tooltip__strelka {
почему не доделана? я сделал стрелку через вектор элемент, она добавлена в html код

2021-11-17 13:41 UTC, GSemikozov requested changes

2021-11-17 13:41 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +.tooltip__strelka {
плохо что стрелка живет своей жизнью параллельно с bubble(
все-таки bubble + стрелка это один элемент.
лучше добавить как псевдо-элемент + отрисовать через css

2021-11-17 19:52 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-11-18 11:50 UTC, GSemikozov requested changes

2021-11-18 11:50 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    text-align: center;
и еще не хватает display: inline-block (у нас ведь иконка триггер, не нужно чтобы блок растягивался на всю доступную ширину по родителю и был блочным элементом)

2021-11-18 11:50 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    top: -130%;
bottom: 100%;
transform: translate(-50%, -8px);

2021-11-18 11:50 UTC, GSemikozov commented on 05-lection3/01-tooltip/index.html
> +<div class="tooltip__center">
лучше чтобы не путать (элемент = ребенок не может содержать в себе блок = родителя) использовать нейтральный класс по типу text-center

2021-11-18 12:43 UTC, TimofeevAnton1980 commented on 05-lection3/01-tooltip/tooltip.css
> +    text-align: center;
Я задал на иконке (класс tooltip__icon): display: inline-block ,
Стоит ли задавать на всём блоке .tooltip?

2021-11-18 16:21 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-11-18 19:46 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    text-align: center;
конечно, ведь тултип - это обычно какая-нибудь подсказка, например в тексте, а как мы в текст добавим блочный элемент? он перенесется но новую строку)

2021-11-18 19:47 UTC, GSemikozov approved these changes

2021-11-18 19:47 UTC, merged