modal
js-tasks-ru/htmlcss-20211021_maestroat pull request #19
Opened 2021-11-13 13:43 UTC by TimofeevAnton1980

2021-11-13 13:43 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-11-14 11:46 UTC, GSemikozov requested changes

2021-11-14 11:46 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.button {
у нас уже есть компонент кнопки, просто нужно подключить ее стили в хтмл, а здесь, в файле компонента, опять же, могут быть только стили этого компонента

2021-11-14 11:46 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.body-grey {
это блок вне компонента, почему мы его описываем здесь?

2021-11-14 11:46 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    width: 428px;
модалка должна растягиваться на 100vh + 100vw, причем позиционироваться через fixed (что позволит привязаться к окну браузера а не к конкретному элементу-родителю). Этому блоку надо задать полупрозрачный фон через rgba

2021-11-14 11:46 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal__block {
а вот этот блок - который, кстати, логичнее назвать .modal__window, - можно позиционировать абсолютом и размещать по середине родителя (ширина будет другой, высоту фиксировать не нужно)

2021-11-14 11:46 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.block__title {
это должен быть элемент модалки, а не элемент какого-то блока .block, поэтому - .block__title -> .modal__block-title

2021-11-14 11:46 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.block__text {
.modal__block-text

2021-11-14 11:46 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    float: right;
про флоаты нужно забыть и никогда не вспоминать. Иконку закрытия лучше разместить абсолютом

2021-11-14 11:46 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    padding-top: 15.33px;
дробные пиксели не используем

2021-11-14 12:19 UTC, TimofeevAnton1980 commented on 05-lection3/02-modal/modal.css
> +.button {
да. понятно.

2021-11-14 12:22 UTC, TimofeevAnton1980 commented on 05-lection3/02-modal/modal.css
> +    float: right;
ясно

2021-11-14 12:23 UTC, TimofeevAnton1980 commented on 05-lection3/02-modal/modal.css
> +    padding-top: 15.33px;
ясно

2021-11-15 16:44 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-11-16 16:02 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-11-16 16:13 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-11-17 07:43 UTC, TimofeevAnton1980 commented on 05-lection3/02-modal/modal.css
> +.body-grey {
Поправил

2021-11-17 07:43 UTC, TimofeevAnton1980 commented on 05-lection3/02-modal/modal.css
> +    width: 428px;
Поправил

2021-11-17 07:44 UTC, TimofeevAnton1980 commented on 05-lection3/02-modal/modal.css
> +.modal__block {
Поправил

2021-11-17 07:44 UTC, TimofeevAnton1980 commented on 05-lection3/02-modal/modal.css
> +.block__title {
Ок

2021-11-17 07:44 UTC, TimofeevAnton1980 commented on 05-lection3/02-modal/modal.css
> +.block__text {
Ок

2021-11-17 07:46 UTC, TimofeevAnton1980 commented on 05-lection3/02-modal/modal.css
> +    float: right;
А почему кстати float так запрещен? я понимаю если на уровне основных блоков страницы, а в этом маленьком блоке, ведь удобно, и работает при любом разрешении?

2021-11-17 13:37 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    float: right;
потому что нужно еще и не забывать на уровне контейнера отменять обтекание через clear: both что совсем не очевидно) в общем, просто изжившая себя технология, по типу как если бы мы использовали таблицы для создания разметки layout-а вместо тех же флексов

2021-11-17 13:38 UTC, GSemikozov approved these changes

2021-11-17 13:38 UTC, merged